# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
      time: '02:00'
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: '/api'
    schedule:
      interval: monthly
      time: '02:00'
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: '/acceptance_tests'
    schedule:
      interval: monthly
      time: '02:00'
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: '/configs'
    schedule:
      interval: monthly
      time: '02:00'
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/api'
    schedule:
      interval: monthly
      time: '02:00'
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: '/acceptance_tests'
    schedule:
      interval: monthly
      time: '02:00'
    ignore:
      - dependency-name: none
