version: 2
updates:
  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: pip
    directory: '/api'
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: pip
    directory: '/acceptance_tests'
    schedule:
      interval: daily
      time: '02:00'

  - package-ecosystem: docker
    directory: '/configs'
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: docker
    directory: '/api'
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: docker
    directory: '/acceptance_tests'
    schedule:
      interval: daily
      time: '02:00'
