version: '2'

services:
  api: &api
    image: camptocamp/mapfish-print-logs:latest
    environment:
      - SQLALCHEMY_URL=postgresql://www-data:www-data@db:5432/print
      - SQLALCHEMY_SLAVE_URL=postgresql://www-data:www-data@db:5432/print
      - STATS_VIEW=1
      # - STATSD_ADDRESS=172.17.0.1:8125
      # - STATSD_PREFIX=suissealpine.dev.api
      - DEVELOPMENT=1
      - LOG_LEVEL=DEBUG
      - C2CWSGIUTILS_LOG_LEVEL=DEBUG
      - SQL_LOG_LEVEL=INFO
      - OTHER_LOG_LEVEL=INFO
      - GUNICORN_LOG_LEVEL=INFO
      - ALEMBIC_LOG_LEVEL=INFO
      - PRINT_A4PRICE=0.05

      # - SCM_URL=http://scm:8080/scm
      # - SCM_URL_EXTERNAL=http://scm:8080/scm
      - GUNICORN_CMD_ARGS=--reload # only one process in order to get consistent stats
      - LOKI_URL=http://loki:3100/
      - LOG_LIMIT=3
      - SHARED_CONFIG_MASTER=/master_config/master/shared_config_manager.yaml
      - GITHUB_TOKEN

      - C2C_AUTH_GITHUB_CLIENT_ID=an-id
      - C2C_AUTH_GITHUB_CLIENT_SECRET=a-secret
      - C2C_AUTH_GITHUB_REPOSITORY=camptocamp/mapfish-print-logs
      - C2C_AUTH_GITHUB_ACCESS_TYPE=pull
      - C2C_AUTH_GITHUB_SECRET=a-secret-long-a-secret
      - C2C_AUTH_GITHUB_PROXY_URL=https://mutualize-int.apps.gs-ch-dev.camptocamp.com/redirect
      - OAUTHLIB_INSECURE_TRANSPORT=1

    volumes:
      - ./api/mapfish_print_logs:/app/mapfish_print_logs:ro
      # - ../c2cwsgiutils/c2cwsgiutils:/usr/local/lib/python3.8/dist-packages/c2cwsgiutils:ro
    volumes_from:
      - configs:ro
    ports:
      - 8480:8080

  api_test_user:
    <<: *api
    environment:
      - TEST_USER=Test

      - SQLALCHEMY_URL=postgresql://www-data:www-data@db:5432/print
      - SQLALCHEMY_SLAVE_URL=postgresql://www-data:www-data@db:5432/print
      - STATS_VIEW=1
      # - STATSD_ADDRESS=172.17.0.1:8125
      # - STATSD_PREFIX=suissealpine.dev.api
      - DEVELOPMENT=1
      - LOG_LEVEL=DEBUG
      - C2CWSGIUTILS_LOG_LEVEL=DEBUG
      - SQL_LOG_LEVEL=INFO
      - OTHER_LOG_LEVEL=INFO
      - GUNICORN_LOG_LEVEL=INFO
      - ALEMBIC_LOG_LEVEL=INFO
      - PRINT_A4PRICE=0.05

      # - SCM_URL=http://scm:8080/scm
      # - SCM_URL_EXTERNAL=http://scm:8080/scm
      - GUNICORN_CMD_ARGS=--reload # only one process in order to get consistent stats
      - LOKI_URL=http://loki:3100/
      - LOG_LIMIT=3
      - SHARED_CONFIG_MASTER=/master_config/master/shared_config_manager.yaml
      - GITHUB_TOKEN

      - C2C_AUTH_GITHUB_CLIENT_ID=an-id
      - C2C_AUTH_GITHUB_CLIENT_SECRET=a-secret
      - C2C_AUTH_GITHUB_REPOSITORY=camptocamp/mapfish-print-logs
      - C2C_AUTH_GITHUB_ACCESS_TYPE=pull
      - C2C_AUTH_GITHUB_SECRET=a-secret-long-a-secret
      - C2C_AUTH_GITHUB_PROXY_URL=https://mutualize-int.apps.gs-ch-dev.camptocamp.com/redirect
      - OAUTHLIB_INSECURE_TRANSPORT=1
    ports:
      - 8481:8080

  configs:
    image: camptocamp/mapfish-print-logs-configs:latest

  db:
    image: camptocamp/postgres:14-postgis-3
    environment:
      POSTGRES_USER: www-data
      POSTGRES_PASSWORD: www-data
      POSTGRES_DB: print
    # Uncomment following line to have database show all incoming SQL statements
    # command: postgres -c log_statement=all
    ports:
      - 15432:5432

  print:
    image: camptocamp/mapfish_print:3.29
    environment:
      LOG_LEVEL: DEBUG
      CATALINA_OPTS: >-
        -Xmx512M -Ddb.username=www-data -Ddb.password=www-data -Ddb.host=db -Ddb.name=print
        -Dmapfish.maxContentLength=4194304
      PGOPTIONS: '-c statement_timeout=30000'
    volumes_from:
      - configs:ro
    links:
      - db
    ports:
      - 8680:8080

  # scm:
  #   image: camptocamp/shared_config_manager:latest
  #   environment:
  #     LOG_LEVEL: DEBUG
  #     MASTER_CONFIG: &master_config |
  #       type: rsync
  #       id: master
  #       source: /master_config/master
  #   ports:
  #     - 8580:8080
  #   volumes_from:
  #     - configs:ro

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-amd64
  #   environment:
  #     ES_JAVA_OPTS: '-Xms512m -Xmx512m'
  #     discovery.type: single-node
  #   ports:
  #     - 9200:9200

  loki:
    image: grafana/loki:2.6.1
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  run:
    image: camptocamp/mapfish-print-logs-acceptance:latest
    environment:
      - GITHUB_TOKEN
    volumes:
      - ./results:/results
      - ./reports:/reports
      - ./acceptance_tests/acceptance:/acceptance_tests/acceptance
      # - ../c2cwsgiutils/c2cwsgiutils:/usr/local/lib/python3.8/dist-packages/c2cwsgiutils:ro
