accounting:
  a4price: 0.05  # A0 is 16x A4; A0 is 1m²; PDF size -> m: pow(1/72 * 2.54/100, 2.0)

sources:
  simple:
    type: git
    repo: https://github.com/mapfish/mapfish-print.git
    key: toto
    sub_dir: examples/src/test/resources/examples/simple
    template_engines:
      - type: shell
        environment_variables: true
      - type: shell
        environment_variables: true
