checks:
  versions: False
  required_workflows: False
  black:
    ignore_patterns_re:
      - api/mapfish_print_logs/templates/source\.html\.mako
  codespell:
    ignore_re:
      - configs/print-apps/simple/countries\.geojson
  dependabot_config: False

version:
  branch_to_version_re:
    - from: ([0-9]+.[0-9]+)
      to: \1
    - from: master
      to: latest

publish:
  pypi:
    packages: []

audit:
  snyk:
    pip_install_arguments:
      - --user
      - --ignore-installed
    pipenv_sync_arguments:
      - --extra-pip-args=--ignore-installed
