checks:
  versions:
    extra_versions:
      - latest
  required_workflows:
    codeql.yaml: False
  black:
    ignore_patterns_re:
      - api/mapfish_print_logs/templates/source\.html\.mako
  codespell:
    ignore_re:
      - configs/print-apps/simple/countries\.geojson

version:
  branch_to_version_re:
    - from: ([0-9]+.[0-9]+)
      to: \1
    - from: master
      to: latest

publish:
  pypi:
    packages: []
