checks:
  versions:
    extra_versions:
      - latest
  required_workflows:
    codeql.yaml: False
  black:
    ignore_patterns_re:
      - api/mapfish_print_logs/templates/source\.html\.mako
  codespell:
    ignore_re:
      - configs/print-apps/simple/countries\.geojson

publish:
  pypi:
    packages: []
