strictness: veryhigh

pylint:
  options:
    max-line-length: 110
  disable:
    - wrong-import-order

pep8:
  disable:
    - E501 # line too long

mypy:
  run: true

mccabe:
  run: false

bandit:
  run: true
  options:
    config: .bandit.yaml
