strictness: veryhigh

pylint:
  options:
    max-line-length: 110
  disable:
    - too-many-arguments
    - too-many-instance-attributes
    - too-many-return-statements
    - too-few-public-methods
    - wrong-import-order
    - missing-timeout # Default timeout set by c2cwsgiutils

pycodestyle:
  disable:
    - E501 # line too long

mypy:
  run: true

mccabe:
  run: false

bandit:
  run: true
  options:
    config: .bandit.yaml
