[tool.mypy]
python_version = "3.8"
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
strict = true

[tool.poetry]
name = "mapfish-print-logs"
version = "0.0.0"
description = "Not used"
authors = []

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
humanfriendly = "10.0"
pyramid-mako = "1.1.0"
c2cwsgiutils = {version = "5.0.0", extras = ["broadcast", "standard"]}
pyramid = "2.0"
sqlalchemy = "1.4.39"

[tool.poetry.dev-dependencies]
prospector = {version = "1.7.7", extras = ["with_bandit", "with_mypy"]}
pylint = "2.14.4"
mypy = "0.961"
flake8 = "4.0.1"
pytest = "7.1.2"
types-setuptools = "57.4.18"
types-pyyaml = "6.0.9"
types-requests = "2.28.0"
typing-extensions = "4.2.0"

[tool.poetry.plugins."paste.app_factory"]
main = "mapfish_print_logs:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
